### ISSUE TITLE
u-boot-menu Modified (by Radxa or by a script) since installation using b39 Rock 5B

### ISSUE THREAD

**Issue by keypunch416** [radxa-build/rock-5b#12]
Just received Rock 5B order few days ago.

First Rock 5B tested is Blue V1.46 8GB.

Image used was [latest Debian Bullseye CLI image b39](https://github.com/radxa-build/rock-5b/releases/download/b39/rock-5b_debian_bullseye_cli_b39.img.xz)

Via ssh performed apt update and apt upgrade that both completed successfully except u-boot related issues that will have separate issues opened.  This is first of the two u-boot related issues. 

During the `apt upgrade` for `u-boot-menu`:

`Preparing to unpack .../u-boot-menu_4.2.2_all.deb ...
Unpacking u-boot-menu (4.2.2) over (4.1.0) ...
Setting up u-boot-menu (4.2.2) ...

Configuration file '/etc/default/u-boot'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** u-boot (Y/I/N/O/D/Z) [default=N] ? d
--- /etc/default/u-boot 2023-09-04 12:35:25.169184661 +0000
+++ /etc/default/u-boot.dpkg-new        2023-04-08 23:12:34.000000000 +0000
@@ -4,6 +4,7 @@
 
 #U_BOOT_ALTERNATIVES="default recovery"
 #U_BOOT_DEFAULT="l0"
+#U_BOOT_PROMPT="0"
 #U_BOOT_ENTRIES="all"
 #U_BOOT_MENU_LABEL="Debian GNU/Linux"
 #U_BOOT_PARAMETERS="ro quiet"
@@ -14,6 +15,3 @@
 #U_BOOT_FDT_OVERLAYS=""
 #U_BOOT_FDT_OVERLAYS_DIR="/boot/dtbo/"
 
-U_BOOT_TIMEOUT="10"
-U_BOOT_PARAMETERS="$(cat /etc/kernel/cmdline)"
-U_BOOT_FDT_DIR="/usr/lib/linux-image-"

Configuration file '/etc/default/u-boot'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** u-boot (Y/I/N/O/D/Z) [default=N] ? `

I chose the default (N) after seeing the differences in between the b39 image and the -u-boot-menu update in part because of the `U_BOOT_TIMEOUT` change.  What is not clear via diff is if the `/etc/default/u-boot` was configured specifically for the [latest Debian Bullseye CLI image b39](https://github.com/radxa-build/rock-5b/releases/download/b39/rock-5b_debian_bullseye_cli_b39.img.xz) and/or the change for `/etc/default/u-boot` was specific for the  [latest Debian Bullseye CLI image b39](https://github.com/radxa-build/rock-5b/releases/download/b39/rock-5b_debian_bullseye_cli_b39.img.xz).

**Comment by RadxaYuntian** [comment]
This is expected. We generally prefer saving our custom configuration in `/usr/share` with unique file name per customary. One particular advantage is that config file in `/usr/share` are generally untouched by the end user, so we can update its content easily without triggering any warnings. Config files located under `/etc` will be checked during package upgrade, and if modified Debian will ask the above question.

However, sometimes the application does not support this scheme, and u-boot-menu was one of them. This feature was only added in [4.2.0](https://salsa.debian.org/debian/u-boot-menu/-/commit/d2429294922f6860ca7b11a39e74ec0a03376cc2), and we were using 4.1.0 before.

We have been shipping newer version of `u-boot-menu` for a while due to 4.0.3 shipped by Debian Bullseye contains several bugs. Currently shipped 4.2.2 fixes [a few more issues](https://github.com/radxa-repo/rbuild/commit/90deb0dc66ba458c583dd4a3c7d402669ca21f15) besides aforementioned config fragments, so we bump the version again and [updated our managed config files](https://github.com/radxa-pkg/radxa-system-config/commit/d7cea71fe1e236592ad184d3ca114aa1146f8988).

In any case, we tried to keep the upgrading process less intrusive. However, when such effort is impossible, we expect the user to choose Y, unless they manually modified the file themselves. In that case they are responsible to compare the difference and merge their changes.
